'use client';
import {useEffect,useRef,useState} from 'react';
import {catalog} from './furniture-library';
import {validLayout} from './layout-data';
import type {EditorState} from './furniture-editor';
export const editAction=(detail:object)=>window.dispatchEvent(new CustomEvent('atlas-edit',{detail}));
export default function EditorPanel({room}:{room:string}){
 const [state,setState]=useState<EditorState>({items:[],selected:null,canUndo:false,canRedo:false,message:''}),[category,setCategory]=useState('All'),[kind,setKind]=useState('upholstered-bed'),[name,setName]=useState('My new layout'),[saved,setSaved]=useState<{id:string;name:string;updated:string}[]>([]),[savedId,setSavedId]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[signIn,setSignIn]=useState(false),[confirmReset,setConfirmReset]=useState(false);
 const file=useRef<HTMLInputElement>(null),current=state.items.find(i=>i.id===state.selected);
 async function refresh(){try{const response=await fetch('/api/layouts');const data:any=await response.json();setSignIn(response.status===401);if(!response.ok)throw new Error(data.error);setSaved(data.layouts);return true}catch(e){setStatus(e instanceof Error?e.message:'Could not read layouts.');return false}}
 useEffect(()=>{const listener=(e:Event)=>setState((e as CustomEvent).detail);window.addEventListener('atlas-editor-state',listener);editAction({type:'request'});try{const draft=JSON.parse(sessionStorage.getItem('atlas-signin-draft')||'null');if(draft&&validLayout(draft.items)){editAction({type:'load',items:draft.items});setName(draft.name);sessionStorage.removeItem('atlas-signin-draft')}}catch{}refresh();return()=>window.removeEventListener('atlas-editor-state',listener)},[]);
 async function save(){setBusy(true);setStatus('Saving…');try{const response=await fetch('/api/layouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,items:state.items})}),data:any=await response.json();if(!response.ok)throw new Error(data.error);await refresh();setSavedId(data.id);setStatus('Layout saved to your account.')}catch(e){setStatus(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 async function load(){setBusy(true);try{const response=await fetch('/api/layouts/'+savedId),data:any=await response.json();if(!response.ok)throw new Error(data.error);if(!validLayout(data.items))throw new Error('This layout is not compatible.');editAction({type:'load',items:data.items});setName(data.name);setStatus('Layout loaded. Undo returns to your previous arrangement.')}catch(e){setStatus(e instanceof Error?e.message:'Load failed.')}finally{setBusy(false)}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,name,items:state.items},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=(name.trim()||'apartment-layout').replace(/[^a-zA-Z0-9 -]/g,'')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Layout file exported.')}
 return <aside className="editor-panel" aria-label="Furniture editor">
  <div className="editor-title"><span>DESIGN YOUR SPACE</span><strong>Edit furniture</strong></div><p>Tap a piece to select it. Drag to move on a 5 cm grid, or use the controls below. Drag empty space to orbit.</p>
  <div className="editor-row"><button disabled={!state.canUndo} onClick={()=>editAction({type:'undo'})}>↶ Undo</button><button disabled={!state.canRedo} onClick={()=>editAction({type:'redo'})}>↷ Redo</button></div>
  <label>Selected furniture<select value={state.selected||''} onChange={e=>editAction({type:'select',id:e.target.value})}><option value="">Choose a piece…</option>{state.items.filter(i=>i.visible).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>
  <div className="selected-furniture"><strong>{current?.name||'Nothing selected'}</strong>{current&&<small>X {current.x.toFixed(2)} m · Z {current.z.toFixed(2)} m · {Math.round(current.rotation*180/Math.PI)%360}°</small>}
   <div className="editor-row"><button aria-label="Move furniture left" disabled={!current} onClick={()=>editAction({type:'move',dx:-.1})}>←</button><button aria-label="Move furniture toward back wall" disabled={!current} onClick={()=>editAction({type:'move',dz:-.1})}>↑</button><button aria-label="Move furniture toward front" disabled={!current} onClick={()=>editAction({type:'move',dz:.1})}>↓</button><button aria-label="Move furniture right" disabled={!current} onClick={()=>editAction({type:'move',dx:.1})}>→</button></div>
   <div className="editor-row"><button disabled={!current} onClick={()=>editAction({type:'rotate',angle:-Math.PI/12})}>↶ 15°</button><button disabled={!current} onClick={()=>editAction({type:'rotate',angle:Math.PI/12})}>↷ 15°</button><button disabled={!current} onClick={()=>editAction({type:'remove'})}>Remove</button></div>
  </div><div className="editor-status" role="status">{state.message||'Furniture can overlap. Check clearances in walk-through mode.'}</div>
  <h3>Furniture library <span>{catalog.length} pieces</span></h3><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);const match=catalog.find(c=>e.target.value==='All'||c.category===e.target.value);if(match)setKind(match.id)}}>{['All',...new Set(catalog.map(c=>c.category))].map(c=><option key={c}>{c}</option>)}</select></label>
  <div className="furniture-catalog" role="group" aria-label="Furniture library">{catalog.filter(c=>category==='All'||c.category===category).map(c=><button key={c.id} aria-pressed={kind===c.id} onClick={()=>setKind(c.id)}><strong>{c.name}</strong><span>{c.size}</span><small>{c.note}</small></button>)}</div>
  <div className="editor-row"><button className="editor-primary" onClick={()=>editAction({type:'add',kind,room})}>Add to room</button><button disabled={!current} onClick={()=>editAction({type:'replace',kind,room})}>Replace selected</button></div>
  <details className="layout-saves" open><summary>Saved layouts</summary><label>Layout name<input maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><button className="editor-primary" disabled={busy||!name.trim()||!state.items.length||signIn} onClick={save}>Save a new layout</button>{signIn&&<a href="/signin-with-chatgpt?return_to=%2F%3Fedit%3D1" target="_top" onClick={()=>{try{sessionStorage.setItem('atlas-signin-draft',JSON.stringify({name,items:state.items}))}catch{}}}>Sign in with ChatGPT to save ↗</a>}{saved.length>0&&<><label>Your saved layouts<select value={savedId} onChange={e=>setSavedId(e.target.value)}><option value="">Choose a saved layout…</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name} · {new Date(s.updated).toLocaleDateString()}</option>)}</select></label><button disabled={!savedId||busy} onClick={load}>Load layout</button></>}
  <div className="editor-row"><button disabled={!state.items.length} onClick={download}>Export file</button><button onClick={()=>file.current?.click()}>Import file</button></div><input hidden ref={file} type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>50000)throw new Error('Layout file is too large.');const data=JSON.parse(await f.text());if(data.version!==1||!validLayout(data.items))throw new Error('This is not a valid apartment layout file.');editAction({type:'load',items:data.items});setName(typeof data.name==='string'?data.name.slice(0,60):'Imported layout');setStatus('Imported. Save to keep this layout in your account.')}catch(err){setStatus(err instanceof Error?err.message:'Import failed.')}}}/><p role="status">{status}</p></details>
  {confirmReset?<div className="editor-row"><button onClick={()=>{editAction({type:'reset'});setConfirmReset(false)}}>Restore original</button><button onClick={()=>setConfirmReset(false)}>Cancel</button></div>:<button onClick={()=>setConfirmReset(true)}>Restore original furniture…</button>}
 </aside>
}
