'use client';
import { useEffect, useState, useCallback } from 'react';
import { Box, ArrowUpRight, Footprints, Layers3, Camera, RotateCcw, Maximize, Sun, Moon, Info, Map, ChevronUp, ChevronDown, ChevronLeft, ChevronRight, MoveUpRight, ArrowLeft } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import Viewport,{type ViewMode} from './viewport';
const rooms=[
{id:'living',name:'Living room',size:'4.8 × 4.4 m',photo:'living-2.png',photo2:'living-1.png',description:'Black leather sectional, cream seating, rust throws and a pale patterned rug. The workstation and television follow the photographs.',evidence:'Two photographs + floor plan',x:2.4,z:5.7},
{id:'kitchen',name:'Kitchen',size:'2.1 × 5.4 m with dining',photo:'kitchen.png',description:'Parallel white cabinetry, black handles, a stainless refrigerator and coil cooker. A narrow passage connects to the laundry.',evidence:'One photograph + floor plan',x:5.95,z:8},
{id:'dining',name:'Dining nook',size:'Open to the living room',photo:'dining.png',description:'A small round timber table sits beside the window, with white shelving along the internal wall.',evidence:'One photograph + floor plan',x:5.95,z:4.8},
{id:'bedroom',name:'Furnished bedroom',size:'2.6 × 3.5 m',photo:'bedroom-1.png',description:'Timber bed, purple floral linen, carpet and a three-blade ceiling fan. Its assignment to this side of the plan is inferred.',evidence:'One photograph + floor plan',x:5.8,z:1.7},
{id:'bedroom2',name:'Empty bedroom',size:'2.6 × 3.5 m',photo:'bedroom-2.png',description:'White walls, marbled tile, a built-in robe and black-framed sliding window. Its assignment to this side of the plan is inferred.',evidence:'One photograph + floor plan',x:1.3,z:1.7},
{id:'bathroom',name:'Bathroom',size:'Between the bedrooms',photo:'bathroom.png',description:'Bath and shower, black rain head and tapware, clear screen, compact vanity and toilet.',evidence:'One photograph + floor plan',x:3.55,z:1.5},
{id:'balcony',name:'Balcony',size:'1.4 × 3.0 m',photo:'exterior.webp',description:'Position and dimensions follow the plan. Balustrade and outside vegetation are approximations; the exterior photo is building context.',evidence:'Floor plan + exterior context',x:-.7,z:6.4},
{id:'laundry',name:'Laundry',size:'2.1 × 1.3 m',photo:'floorplan.png',description:'The laundry is shown on the plan, but there is no interior photograph. Its fixtures and finishes are inferred.',evidence:'Floor plan only · inferred interior',x:5.95,z:10.35}
];
function MiniMap({active,onSelect,position}:{active:string;onSelect:(id:string)=>void;position:[number,number]}){return <svg viewBox="-2 -1 10 13" className="mini-map" aria-label="Apartment navigation plan" role="group"><path d="M0 0H7.1V11H4.8V7.9H0Z" fill="#30464e" stroke="#90a3a8" strokeWidth=".08"/><path d="M0 3.5H2.6V0M4.5 0V3.5H7.1M2.6 2.5H4.5M4.8 7.9V6M4.8 9.7H7.1M0 4.9H-1.4V7.9H0" fill="none" stroke="#91a5aa" strokeWidth=".07"/>{rooms.map(r=><g key={r.id} role="button" tabIndex={0} aria-label={'Go to '+r.name} onClick={()=>onSelect(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(r.id)}}}><circle cx={r.x} cy={r.z} r={.36} fill={active===r.id?'#b5ead7':'#20343e'} stroke={active===r.id?'#b5ead7':'#8ba1a7'} strokeWidth=".05"/><text x={r.x} y={r.z+.1} fontSize=".29" fill={active===r.id?'#17332b':'#e8f4f1'} textAnchor="middle">{rooms.indexOf(r)+1}</text></g>)}{position[0]>-2&&position[0]<8&&position[1]<12&&<circle cx={position[0]} cy={position[1]} r={.12} fill="#fff" stroke="#223a32" strokeWidth=".04"/>}</svg>}
export default function Home(){
 const [mode,setMode]=useState<ViewMode>('dollhouse'),[room,setRoom]=useState('living'),[reset,setReset]=useState(0),[day,setDay]=useState(true),[ready,setReady]=useState(false),[details,setDetails]=useState(false),[plan,setPlan]=useState(false),[compare,setCompare]=useState(false),[photoAlt,setPhotoAlt]=useState(false),[position,setPosition]=useState<[number,number]>([2.4,5.7]);
 const selected=rooms.find(r=>r.id===room)!;const jump=useCallback((id:string)=>{setRoom(id);setMode('walk');setReset(v=>v+1);setPhotoAlt(false)},[]);const report=useCallback((x:number,z:number)=>setPosition([x,z]),[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'navigate_apartment',description:'Move the apartment viewer to a room or dollhouse overview.',inputSchema:{type:'object',properties:{room:{type:'string',enum:rooms.map(r=>r.id)},view:{type:'string',enum:['walk','dollhouse','photos']}},required:['room','view'],additionalProperties:false},execute:async(input:any)=>{if(!rooms.some(r=>r.id===input.room)||!['walk','dollhouse','photos'].includes(input.view))throw new Error('Unknown room or view');setRoom(input.room);setMode(input.view);setReset(v=>v+1);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {room:input.room,view:input.view}},annotations:{readOnlyHint:false}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const movement=(action:string)=>window.dispatchEvent(new CustomEvent('atlas-move',{detail:{action}}));
 return <main className="atlas"><header><div className="brand"><Box/><strong>APARTMENT ATLAS</strong></div><span className="study-tag">YOUR APARTMENT / SPATIAL STUDY</span><a href="/progress">Build journal <ArrowUpRight size={16}/></a></header>
 <div className="viewer-heading"><div><h1>Your apartment, in perspective.</h1><span className="reconstruction-note"><i/> Photo-guided reconstruction <button onClick={()=>setDetails(true)} aria-label="About reconstruction accuracy"><Info size={15}/></button></span></div><Tabs value={mode} onValueChange={v=>{setMode(v as ViewMode);setCompare(false)}} className="mode-tabs"><TabsList><TabsTrigger value="dollhouse"><Layers3 size={16}/>Dollhouse</TabsTrigger><TabsTrigger value="walk"><Footprints size={16}/>Walk through</TabsTrigger><TabsTrigger value="photos"><Camera size={16}/>Photos</TabsTrigger></TabsList></Tabs></div>
 <div className="workspace"><section className={'scene-panel '+(mode==='photos'?'photo-mode':'')} aria-label="Apartment viewer"><Viewport mode={mode} room={room} reset={reset} daylight={day} onReady={()=>setReady(true)} onPosition={report}/>
 {mode==='photos'&&<div className="full-photo"><img src={'/photos/'+(photoAlt&&selected.photo2?selected.photo2:selected.photo)} alt={'Original source: '+selected.name}/><div className="photo-caption">ORIGINAL PHOTOGRAPH{room==='laundry'?' · FLOOR PLAN':room==='balcony'?' · EXTERIOR CONTEXT':''}</div></div>}
 <div className="scene-top"><span className="scene-badge"><i/>{mode==='dollhouse'?'DOLLHOUSE OVERVIEW':selected.name.toUpperCase()}</span><div className="scene-tools">{mode!=='photos'&&<><button title="Reset view" aria-label="Reset view" onClick={()=>setReset(v=>v+1)}><RotateCcw size={18}/></button><button title="Change lighting" aria-label={day?'Switch to soft evening light':'Switch to daylight'} onClick={()=>setDay(!day)}>{day?<Sun size={18}/>:<Moon size={18}/>}</button></>}<button title="Fullscreen" aria-label="Fullscreen viewer" onClick={()=>{const el=document.querySelector('.scene-panel');if(!document.fullscreenElement)el?.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.()}}><Maximize size={18}/></button></div></div>
 {compare&&mode!=='photos'&&<div className="comparison"><img src={'/photos/'+(photoAlt&&selected.photo2?selected.photo2:selected.photo)} alt={'Reference photograph: '+selected.name}/><span>SOURCE REFERENCE · {selected.name}</span><button onClick={()=>setCompare(false)} aria-label="Close reference">×</button></div>}
 {mode!=='photos'&&<div className="map-card"><div><span>FLOOR GUIDE</span><button onClick={()=>setPlan(true)} aria-label="Open supplied floor plan"><MoveUpRight size={15}/></button></div><MiniMap active={mode==='walk'?room:''} onSelect={jump} position={mode==='walk'?position:[20,20]}/><small>Choose a room to step inside</small></div>}
 {mode==='walk'&&<div className="walk-pad" aria-label="Movement controls">{[['w',ChevronUp,'Move forward'],['a',ChevronLeft,'Move left'],['s',ChevronDown,'Move backward'],['d',ChevronRight,'Move right']].map(([key,Icon,label]:any)=><button key={key} className={'move-'+key} aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);movement(key)}} onPointerUp={()=>movement('stop')} onPointerCancel={()=>movement('stop')} onLostPointerCapture={()=>movement('stop')} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')movement(key)}} onKeyUp={()=>movement('stop')}><Icon size={20}/></button>)}</div>}
 <div className="scene-help">{mode==='dollhouse'?<><b>Drag</b> to orbit <span/> <b>Scroll</b> to zoom</>:mode==='walk'?<><b>Drag</b> to look <span/><b>W A S D</b> to move <span/> <b>Double-click</b> floor to approach</>:<>Source photographs retain their original detail.</>}</div>
 {!ready&&mode!=='photos'&&<div className="loading-model">Preparing your apartment…</div>}
 </section>
 <aside className="room-detail"><div className="room-number">{String(rooms.indexOf(selected)+1).padStart(2,'0')} <span>/ 08 SPACES</span></div><h2>{mode==='dollhouse'?'Make yourself at home.':selected.name}</h2><p className="room-size">{mode==='dollhouse'?'Two bedrooms. One connected space.':selected.size}</p><p>{mode==='dollhouse'?'Orbit the apartment to understand its layout, then step into any room. The model follows the supplied floor plan and the details visible in your photographs.':selected.description}</p><button className="primary-button" onClick={()=>mode==='walk'?setMode('dollhouse'):jump(room)}>{mode==='walk'?<><Layers3 size={17}/> Back to dollhouse</>:<><Footprints size={17}/> Step inside {mode==='dollhouse'?'':selected.name.toLowerCase()}</>}</button><div className="detail-divider"/><button className="reference-card" onClick={()=>{if(mode==='photos'){setMode('walk');setCompare(true)}else setCompare(!compare)}}><div><img src={'/photos/'+(photoAlt&&selected.photo2?selected.photo2:selected.photo)} alt={selected.name+' source preview'}/><span><Camera size={17}/></span></div><strong>{mode==='photos'?'Compare with the 3D room':compare?'Hide reference':'Compare with the source'}</strong><small>{selected.evidence}</small></button>{selected.photo2&&<button className="text-button" onClick={()=>setPhotoAlt(!photoAlt)}>Show {photoAlt?'first':'other'} living-room angle <ArrowUpRight size={14}/></button>}<div className="accuracy-note"><Info size={16}/><p>Reconstructed geometry. Unseen details are inferred. This is not a Gaussian scan.</p></div><button className="text-button" onClick={()=>setPlan(true)}><Map size={16}/> View the original floor plan</button></aside></div>
 <nav className="room-strip" aria-label="Choose a room">{rooms.map((r,i)=><button key={r.id} aria-pressed={room===r.id&&mode!=='dollhouse'} onClick={()=>{setRoom(r.id);setPhotoAlt(false);if(mode!=='photos')jump(r.id)}}><img src={'/photos/'+r.photo} alt=""/><span><small>{String(i+1).padStart(2,'0')}</small>{r.name}</span><ArrowUpRight size={14}/></button>)}</nav><footer><span>Built from your photographs & floor plan</span><span>Scale is approximate · not for measurement</span><a href="/progress">See the work evolve ↗</a></footer>
 <Dialog open={details} onOpenChange={setDetails}><DialogContent className="atlas-dialog"><DialogTitle>What this reconstruction can tell you</DialogTitle><DialogDescription>The layout and visible objects are modeled from your sources. They have not been measured by a 3D scan.</DialogDescription><p>Room dimensions follow the marketing plan. Ceiling height, exact openings, unseen surfaces, bedroom assignment, laundry fittings and outdoor context are inferred. The garage is not placed because the plan explicitly says “not in position”.</p><p><strong>For a true Gaussian splat:</strong> capture a slow, continuous walkthrough that connects every room. Move around each object and doorway with substantial overlap, keep lighting steady, and include views above and below eye level. Turning in place is not enough to establish depth.</p><p>Original photographs are available in Photos and Compare. The live journal records independent reviews and remaining gaps.</p><a href="https://colmap.github.io/tutorial" target="_blank" rel="noreferrer">Read the capture guidance ↗</a></DialogContent></Dialog>
 <Dialog open={plan} onOpenChange={setPlan}><DialogContent className="atlas-dialog plan-dialog"><DialogTitle>The supplied floor plan</DialogTitle><DialogDescription>Marketing dimensions are approximate. Garage placement is unspecified.</DialogDescription><img src="/photos/floorplan.png" alt="Original apartment floor plan with room dimensions and detached garage marked not in position"/></DialogContent></Dialog>
 </main>
}

