import {env} from 'cloudflare:workers';
import {validLayout} from '../../layout-data';
export const dynamic='force-dynamic';
type Store={LAYOUTS:R2Bucket};
function identity(request:Request){return request.headers.get('oai-authenticated-user-id')}
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
async function prefix(user:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(user));return 'layouts/'+Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')+'/'}
export async function GET(request:Request){const user=identity(request);if(!user)return json({error:'Sign in with ChatGPT to save and load your layouts.'},401);try{const store=(env as unknown as Store).LAYOUTS;const list=await store.list({prefix:await prefix(user),include:['customMetadata'],limit:100} as R2ListOptions & {include:string[]});return json({layouts:list.objects.map(o=>({id:o.key.split('/').pop(),name:o.customMetadata?.name||'Layout',updated:o.uploaded.toISOString()}))})}catch{return json({error:'Saved layouts are unavailable. Try again shortly.'},503)}}
export async function POST(request:Request){const user=identity(request);if(!user)return json({error:'Sign in with ChatGPT to save your layouts.'},401);if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'Invalid request origin.'},403);try{const raw=await request.text();if(raw.length>50000)return json({error:'Layout is too large.'},413);const body=JSON.parse(raw);if(typeof body.name!=='string'||!body.name.trim()||body.name.length>60||!validLayout(body.items))return json({error:'Invalid layout.'},400);const store=(env as unknown as Store).LAYOUTS,p=await prefix(user),list=await store.list({prefix:p,limit:100});if(list.objects.length>=100)return json({error:'You have reached 100 saved layouts. Export a copy instead.'},409);const id=crypto.randomUUID();await store.put(p+id,JSON.stringify({name:body.name.trim(),items:body.items}),{httpMetadata:{contentType:'application/json'},customMetadata:{name:body.name.trim()}});return json({id},201)}catch{return json({error:'Could not save this layout. Export a copy or try again.'},503)}}
